### ISSUE TITLE
TypeError: slice indices must be integers

### ISSUE THREAD

**Issue by studiawan** [ottokart/punctuator#11]
I run punctuator with a fresh clone from GitHub. The command is `python main.py model`, but I got an error below:

Converting data...

Traceback (most recent call last):
  File "main.py", line 40, in <module>
    converter.convert_files(conf.PHASE1["TRAIN_DATA"], vocabulary, conf.PUNCTUATIONS, conf.BATCH_SIZE, False, PHASE1_TRAIN_PATH)
  File "/home/hudan/Git/punctuator/src/converter.py", line 44, in convert_files
    inputs = np.array(inputs, dtype=dtype)[:batch_size*num_batches].reshape((batch_size, num_batches)).T
TypeError: slice indices must be integers or None or have an __index__ method

I tested punctuator using Python 2.7.12 and Numpy 1.14.3.

**Comment by studiawan** [comment]
I convert variable num_batches to an integer in converter.py and add this command line 43:

`num_batches = int(num_batches)`

It is working well now. Thank you.
